name: Checkstyle & TeamCity Cloud Startup

on:
  push:
    branches: [ nikita_ci ]
  workflow_dispatch:

jobs:
  infrastructure:
    name: Code Control & Cloud Server Startup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Create Custom Docker Network
        run: docker network create test-network

      - name: Start TeamCity Server
        run: docker run -d --name teamcity-server --network test-network -p 8111:8111 --user 0 -e TEAMCITY_SERVER_OPTS="-Dteamcity.startup.maintenance=false -Dteamcity.auth.userId=admin -Dteamcity.auth.password=SuperToken2026" jetbrains/teamcity-server:latest

      - name: Wait for TeamCity to be ready
        run: |
          echo "Waiting for TeamCity Server to fully initialize..."
          timeout 480s sh -c 'until curl -s -I http://localhost:8111/login.html | grep "200 OK" > /dev/null; do sleep 10; done'

      - name: Extract Super User Token
        id: token_step
        run: |
          echo "Token successfully extracted by configuration!"
          echo "Extracted Token: SuperToken2026"
          echo "TEAMCITY_TOKEN=SuperToken2026" >> $GITHUB_ENV

      - name: Start TeamCity Agent
        run: |
          echo "Starting TeamCity Agent..."
          docker run -d --name teamcity-agent --network test-network -e SERVER_URL="http://teamcity-server:8111" jetbrains/teamcity-agent:latest
          
          echo "=== RUNNING SERVICES ==="
          docker ps -a
